# Compilation dockerfile
FROM openjdk:8-jdk
MAINTAINER Ryan Brown <ryanbrown.dev@gmail.com>

RUN apt-get update && \
    apt-get clean && \
    rm /var/lib/apt/lists/*_*

RUN mkdir -p /app/api

# setup local container user
ENV USER_ID 1000
ENV GROUP_ID 1000
RUN groupadd -g ${GROUP_ID} api
RUN useradd -u ${USER_ID} -g api -s /bin/bash -m -d /app/api api
RUN chown api:api -R /app/api
USER api
VOLUME ["/app/api"]
WORKDIR /app/api

EXPOSE 8080
ENTRYPOINT ["./gradlew"]